services:
    key-file:
        image: docker.io/mongodb/mongodb-enterprise-server:7.0-ubi8
        volumes:
            - keys:/keys
        entrypoint:
            - /bin/sh
            - -c
            - |
                echo "Installing openssl..."
                yum install -y openssl
                echo "Generating keyfile..."
                openssl rand -base64 741 | tr -d "+/=\n" > /keys/keyfile
                if [ $? -ne 0 ]; then
                    echo "Failed to generate keyfile"
                    exit 1
                fi
                echo "Setting permissions on keyfile..."
                chmod 600 /keys/keyfile
                if [ $? -ne 0 ]; then
                    echo "Failed to set permissions on keyfile"
                    exit 1
                fi
                echo "Keyfile setup complete."

    mongod:
        image: docker.io/mongodb/mongodb-enterprise-server:7.0-ubi8
        hostname: mongod
        depends_on:
            key-file:
                condition: service_completed_successfully
        ports:
            - "127.0.0.1:27018:27017"
        volumes:
            - mongodb_test:/data/db
            - keys:/keys
        environment:
            MONGO_INITDB_ROOT_USERNAME: testuser
            MONGO_INITDB_ROOT_PASSWORD: testpass
            MONGO_INITDB_DATABASE: test
        entrypoint:
            - /bin/sh
            - -c
            - |
                python3 /usr/local/bin/docker-entrypoint.py \
                  --dbpath "/data/db" \
                  --keyFile "/keys/keyfile" \
                  --replSet "rs-localdev" \
                  --maxConns 32200 \
                  --setParameter "mongotHost=mongot:27027" \
                  --setParameter "searchIndexManagementHostAndPort=mongot:27027" \
                  --transitionToAuth

    mongod-init-rs:
        image: docker.io/mongodb/mongodb-enterprise-server:7.0-ubi8
        hostname: mongod-init-rs
        depends_on:
            - mongod
        entrypoint:
            - /bin/sh
            - -c
            - |
                echo "Initialising replica set..."
                until mongosh --host mongod --eval "db.adminCommand('ping')"; do
                    sleep 1
                done
                mongosh --host mongod --eval "rs.initiate()"
                echo "Replica set initialised"

    mongot:
        image: docker.io/mongodb/mongodb-atlas-search:preview
        hostname: mongot
        depends_on:
            mongod-init-rs:
                condition: service_completed_successfully
        volumes:
            - mongot_test:/var/lib/mongot
            - keys:/keys
        environment:
            - MONGOD_HOST_AND_PORT=mongod:27017
            - KEY_FILE=/keys/keyfile
            - DATA_DIR=/var/lib/mongot

volumes:
    mongot_test:
    mongodb_test:
    keys:

networks:
    local-atlas-network:
        ipam:
            config:
                - subnet: 10.89.0.0/24
