services:
    mongod:
        image: docker.io/mongodb/mongodb-enterprise-server:7.0-ubi8
        hostname: mongod
        ports:
            - "127.0.0.1:27018:27017"
        volumes:
            - mongodb_test:/data/db
            - ./src/test/resources/mongo-keyfile:/keys/keyfile:ro
        environment:
            MONGODB_INITDB_ROOT_USERNAME: testuser
            MONGODB_INITDB_ROOT_PASSWORD: testpass
            MONGODB_INITDB_DATABASE: test
        entrypoint:
            - /bin/sh
            - -c
            - |
                python3 /usr/local/bin/docker-entrypoint.py \
                  --dbpath "/data/db" \
                  --keyFile "/keys/keyfile" \
                  --replSet "rs-localdev" \
                  --maxConns 32200 \
                  --setParameter "mongotHost=mongot:27027" \
                  --setParameter "searchIndexManagementHostAndPort=mongot:27027" \
                  --transitionToAuth

    mongod-init-rs:
        image: docker.io/mongodb/mongodb-enterprise-server:7.0-ubi8
        hostname: mongod-init-rs
        depends_on:
            - mongod
        entrypoint:
            - /bin/sh
            - -c
            - |
                echo "Initialising replica set..."
                until mongosh --host mongod --eval "db.adminCommand('ping')"; do
                    sleep 1
                done
                mongosh --host mongod --eval "rs.initiate()"
                echo "Replica set initialised"

    mongot:
        image: docker.io/mongodb/mongodb-atlas-search:preview
        hostname: mongot
        depends_on:
            mongod-init-rs:
                condition: service_completed_successfully
        volumes:
            - mongot_test:/var/lib/mongot
            - ./src/test/resources/mongo-keyfile:/keys/keyfile:ro
        environment:
            - MONGOD_HOST_AND_PORT=mongod:27017
            - KEY_FILE=/keys/keyfile
            - DATA_DIR=/var/lib/mongot

volumes:
    mongot_test:
    mongodb_test:

networks:
    local-atlas-network:
        ipam:
            config:
                - subnet: 10.89.0.0/24
