---
compile-version-key: ${compile-version-key}

spring:
    cloud:
        aws:
            s3:
                region: us-west-2
                bucket: ${s3.bucket}
    config:
        import: aws-secretsmanager:/staging/kogo-content-backend/application.properties
    data:
        mongodb:
            database: ${mongodb.database}
            uri: ${mongodb.uri}
            username: ${mongodb.username}
            password: ${mongodb.password}
            auto-index-creation: true

kogo-api:
    base-url: "https://api.staging.kogocampus.com"

filehandler:
    prefix: files

meilisearch:
    host: ${meilisearch.host}
    apikey: ${meilisearch.apikey}
