---
compileVersionKey: ${secrets.compileVersionKey}

spring:
    config:
        import: aws-secretsmanager:/staging/kogo-content-backend/application.properties
    data:
        mongodb:
            database: ${secrets.mongodb.database}
            uri: ${secrets.mongodb.uri}
            username: ${secrets.mongodb.username}
            password: ${secrets.mongodb.password}
            auto-index-creation: true

external:
    auth:
        url: "https://api.staging.kogocampus.com/student"

filehandler:
    prefix: files

meilisearch:
    host: ${secrets.meilisearch.host}
    apikey: ${secrets.meilisearch.apikey}

aws:
    s3:
        bucket: ${secrets.aws.s3.bucket}
