server:
  port: 8080

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /index.html

spring:
  application:
    name: kogo-content-backend
  data:
    mongodb:
        database: kogocontent
        uri: mongodb://localhost:27017/kogocontent
        username: admin
        password: password
        auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://kogo-dev.auth.us-west-2.amazoncognito.com
          jwk-set-uri: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_Onci94rlj/.well-known/jwks.json

management:
  endpoints:
    web:
      base-path: /-
      exposure:
        include: health

filehandler:
  provider: local
  localMountLocation: local

meilisearch:
  host: http://localhost:7700
  apiKey: eGF8XnMo/fQeXWubiKvH24u55RQ+uuBEbQX9R1nkj7s=
