---
compile-version-key: ${compile-version-key}

kogo-api:
    base-url: "https://api.staging.kogocampus.com"

filehandler:
    prefix: files

spring:
    config:
        import: aws-secretsmanager:/staging/kogo-content/application.properties
    data:
        mongodb:
            database: ${mongodb.database}
            uri: ${mongodb.uri}
            username: ${mongodb.username}
            password: ${mongodb.password}
            auto-index-creation: true

aws:
    s3:
        bucket: ${s3.bucket}
        region: ${s3.region}

meilisearch:
    host: ${meilisearch.host}
    apikey: ${meilisearch.apikey}

sentry:
    dsn: ${sentry.dsn}
    traces-sample-rate: 1.0
