server:
  port: 8080

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /index.html

spring:
    application:
        name: kogo-content-backend
    profiles:
        active: "local"

cloud:
    aws:
        region:
            static: us-west-2
        credentials:
            profile-name: default

management:
    endpoints:
        web:
            base-path: /-
            exposure:
                include: health
