server:
  port: 8080

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /index.html

spring:
    cloud:
        aws:
            secretsmanager:
                region: us-west-2
    application:
        name: kogo-content-backend
    profiles:
        default: "local"

management:
    endpoints:
        web:
            base-path: /-
            exposure:
                include: health
