server:
  port: 8080

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /index.html

spring:
    application:
        name: kogo-content-backend
    profiles:
        active: "local"
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://kogo-dev.auth.us-west-2.amazoncognito.com
                    jwk-set-uri: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_Onci94rlj/.well-known/jwks.json

cloud:
    aws:
        region:
            static: us-west-2
        credentials:
            profile-name: default

management:
    endpoints:
        web:
            base-path: /-
            exposure:
                include: health
