---
compile-version-key: ${COMPILE_VERSION_KEY}

spring:
    cloud:
        aws:
            s3:
                region: ${S3_REGION}
                bucket: ${S3_BUCKET}
    data:
        mongodb:
            database: ${MONGODB_DATABASE}
            uri: ${MONGODB_URI}
            username: ${MONGODB_USERNAME}
            password: ${MONGODB_PASSWORD}
            auto-index-creation: true

kogo-api:
    base-url: "https://api.staging.kogocampus.com"

filehandler:
    prefix: files

meilisearch:
    host: ${MEILISEARCH_HOST}
    apikey: ${MEILISEARCH_APIKEY}
