name: build and test
on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
    pull_request:
        branches:
            - main
        paths:
            - 'src/**'

jobs:
    deploy:
        runs-on: [ubuntu-latest]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                ref: ${{ github.event.pull_request.head.sha }}

            - uses: actions/setup-java@v3
              with:
                distribution: temurin
                java-version: 21

            - name: Setup AWS CLI
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-west-2

            - name: Build with Gradle
              run: ./gradlew build --no-daemon

            - name: Run Unit Tests
              run: ./gradlew test --no-daemon


