name: build and test
on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
    pull_request:
        branches:
            - main
        paths:
            - 'src/**'
    workflow_dispatch:

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}

            - uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: 21

            - name: Install MongoDB
              run: |
                  sudo apt-get update
                  sudo apt-get install -y gnupg curl
                  curl -fsSL https://www.mongodb.org/static/pgp/server-7.0.asc | \
                    sudo gpg --dearmor -o /usr/share/keyrings/mongodb-archive-keyring.gpg
                  echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-archive-keyring.gpg ] https://repo.mongodb.org/apt/ubuntu jammy mongodb-org/7.0 multiverse" | \
                    sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
                  sudo apt-get update
                  sudo apt-get install -y mongodb-org

            - name: Start MongoDB
              run: |
                  sudo systemctl start mongod
                  sudo systemctl status mongod --no-pager

            - name: Wait for MongoDB to start
              run: |
                  until nc -z -v -w30 localhost 27017
                  do
                    echo "Waiting for MongoDB..."
                    sleep 5
                  done

            - name: Build
              run: ./gradlew build --no-daemon

            - name: Run Tests
              run: ./gradlew test --no-daemon
