name: deploy swagger docs
on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
    workflow_dispatch:

jobs:
    deploy-docs:
        runs-on: [ubuntu-latest]

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
              with:
                ref: ${{ github.event.pull_request.head.sha }}

            - uses: actions/setup-java@v3
              with:
                distribution: temurin
                java-version: 21

            - name: Setup AWS CLI
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-west-2

            - name: Generate OpenAPI Documentation
              run: ./gradlew generateOpenApiDocs

            #- name: Upload Swagger UI and JSON to S3
            #  run: |
            #      aws s3 sync build/swagger-ui/ s3://kogo-content-backend-swagger-ui/ --delete
            #  env:
            #      AWS_REGION: us-west-2

            -  name: Build and Deploy to GitHub Pages
               uses: peaceiris/actions-gh-pages@v3
               with:
                   deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                   publish_dir: ./src/main/swagger-ui
                   publish_branch: gh-pages

