name: Deploy Staging Image

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
    workflow_dispatch:

env:
    AWS_REGION: us-west-2
    ECR_REPOSITORY: 992382730467.dkr.ecr.us-west-2.amazonaws.com/staging-kogo-content-backend
    SPRING_PROFILES_ACTIVE: stg

jobs:
    deploy-staging:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: 21

            - name: Setup AWS CLI
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR
              id: ecr_login
              uses: aws-actions/amazon-ecr-login@v1

            - name: Generate Timestamp
              id: timestamp
              run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

            - name: Build with Gradle (stg profile)
              run: ./gradlew clean build -x test -PactiveProfile=${{ env.SPRING_PROFILES_ACTIVE }}

            - name: Build Docker image
              run: |
                  COMMIT_HASH=${{ github.sha }}
                  docker build -t ${{ env.ECR_REPOSITORY }}:latest -t ${{ env.ECR_REPOSITORY }}:${{ env.TIMESTAMP }}-${COMMIT_HASH::7} .

            - name: Push Docker images to ECR
              run: |
                  docker push ${{ env.ECR_REPOSITORY }} --all-tags
